title: "hanaoverride's notebook"
description: "잡다한거 적는 곳입니다"
url: "https://hanaoverride.github.io"
baseurl: "" # GitHub Pages user/organization site면 공백 유지

# 사이트 기본 메타
lang: ko-KR
timezone: Asia/Seoul

# 저작자 정보
author:
  name: "이하나"
  email: "hanaoverride@gmail.com"
  url: "https://github.com/hanaoverride"

# 테마 & 스타일
theme: jekyll-theme-hacker
sass:
  sass_dir: assets/css

# 플러그인 (GitHub Pages 호환 목록 내)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# 마크다운 & 하이라이터
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# 퍼머링크 구조 (카테고리 포함)
permalink: /:categories/:year/:month/:day/:title/

# 페이지 / 포스트 기본값
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false

# 컬렉션 (필요시 확장 용도) — 지금은 _pages 폴더를 일반 페이지처럼 사용
# (과거 _pages 컬렉션은 표준 _posts 마이그레이션 후 제거)
# collections: (필요시 재도입)

# SEO / 피드 설정
feed:
  path: feed.xml
seo:
  type: "Blog"

# 빌드 제외
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# 캐시/출력 폴더 (GitHub Pages가 자동 무시하지만 명시)
keep_files: [".git"]

# 향후 설정 메모:
# - 댓글(utterances/disqus) 추가 시 comments 설정 확장
# - 태그 페이지 생성 스크립트 추가 가능

# 라이선스 (Creative Commons 표시용 재사용 변수)
license:
  name: "Creative Commons Attribution-ShareAlike 4.0 International"
  short: "CC BY-SA 4.0"
  spdx: "CC-BY-SA-4.0"
  url: "https://creativecommons.org/licenses/by-sa/4.0/"
  # CC 공식 아이콘 (SVG) 또는 배지 이미지 URL (원하면 커스텀 가능)
  badge_svg: "https://licensebuttons.net/l/by-sa/4.0/88x31.png"
  attribution_name: "{{ site.author.name }}"
  attribution_url: "{{ site.url }}{{ site.baseurl }}"
  # JSON-LD 출력 여부 (원하면 off)
  jsonld: true
