title: "hanaoverride's notebook"
description: "잡다한거 적는 곳입니다"
url: "https://hanaoverride.github.io"
baseurl: "" # GitHub Pages user/organization site면 공백 유지

# 사이트 기본 메타
lang: ko-KR
timezone: Asia/Seoul

# 저작자 정보
author:
  name: "이하나"
  email: "hanaoverride@gmail.com"
  url: "https://github.com/hanaoverride"

# 테마 & 스타일
theme: jekyll-theme-hacker
sass:
  sass_dir: assets/css

# 플러그인 (GitHub Pages 호환 목록 내)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 마크다운 & 하이라이터
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# 퍼머링크 구조 (카테고리 포함)
permalink: /:categories/:year/:month/:day/:title/

# 페이지 / 포스트 기본값
defaults:
  - scope:
      path: "_pages"
    values:
      layout: post
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false

# 컬렉션 (필요시 확장 용도) — 지금은 _pages 폴더를 일반 페이지처럼 사용
collections:
  pages:
    output: true
    permalink: /:path/

# SEO / 피드 설정
feed:
  path: feed.xml
seo:
  type: "Blog"

# 빌드 제외
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# 캐시/출력 폴더 (GitHub Pages가 자동 무시하지만 명시)
keep_files: [".git"]

# 향후 설정 메모:
# - 댓글(utterances/disqus) 추가 시 comments 설정 확장
# - 태그 페이지 생성 스크립트 추가 가능
